### PR TITLE
 bugfix #15 added check before sourcing kube-fzf

### PR DESCRIPTION
**Pull request by viveksoundrapandi**
My experience with shell script is minimal. The solution is to check if the current directory is the git repo of kube-fzf and source the file accordingly. Wanted to give a try as its a good-first issue. 

Let me know what's the right approach.

### CODE REVIEW

**Comment by arunvelsriram** [comment]
I think the same problem as mentioned in #15 will occur again for the file `fzf-utils.sh`. May be duplication is okay?

Instead of checking if the current directory contains `kube-fzf.sh` we could use a env variable flag called `DEVELOPMENT=true` and toggle the `source` command. 

Another approach am thinking is to pass `KUBE_FZF_PATH=./kube-fzf.sh` and do `source ${KUBE_FZF_PATH}`.

Thoughts?

**Comment by dineshba** [comment]
I am leaning towards `Another approach am thinking is to pass KUBE_FZF_PATH=./kube-fzf.sh and do source ${KUBE_FZF_PATH}.`

Reasons:
1) Env `DEVELOPMENT` looks very common. It may produce unintentional behavior to the user.
2) i) We have to ship `fzf-utils.sh` file to the user. ii) How will we source `fzf-utils.sh` ? In current directory or in path ? Recursion starts :-P

**Comment by viveksoundrapandi** [comment]
> I think the same problem as mentioned in #15 will occur again for the file `fzf-utils.sh`. May be duplication is okay?
> 
> Instead of checking if the current directory contains `kube-fzf.sh` we could use a env variable flag called `DEVELOPMENT=true` and toggle the `source` command.
> 
> Another approach am thinking is to pass `KUBE_FZF_PATH=./kube-fzf.sh` and do `source ${KUBE_FZF_PATH}`.
> 
> Thoughts?

Yes ENV variable sounds the ideal way. BTW, my approach is to check if the current directory is kube-fzf rather than if the current directory holds kube-fzf.sh. THis would avoid the problem of sourcing fzf-utils. I decided to use this approach, as we are directly mounting the findpod and other commands to /usr/local rather than /usr/local/kube-fzf/*

**Comment by viveksoundrapandi** [comment]
@dineshba is the above implementation of checking with ENV var fine?

**Comment by dineshba** [comment]
Looks good to me. @arunvelsriram Can i merge this PR?

**Comment by arunvelsriram** [comment]
Yes please.

**Comment by dineshba** [comment]
@viveksoundrapandi Thanks for the PR 👍

**Pull request merged**
